### ISSUE TITLE
The link to the Paper you used for implementing PID Control

### ISSUE THREAD

**Issue by shanki98** [JacopoPan/gym-pybullet-drones#12]
Hey Jacob!

I'm quite new to drones and I saw your controller but I was a little confused, So I wanted to replicate your PID COntroller on my Model. I tried using your gains, but the X and Y did not settle. So can you maybe reference the paper you used to implement the PID controller or Maybe the architecture that you have used.. Since it is a cascaded control architecture, I don't know what is the frequency at which your attitude controller works and the frequency at which the position controller works

**Comment by JacopoPan** [comment]
Hi @shanki98 

there are a few implementations of 1, 2 and 3D controllers in the repository whose source you can peek at.
None of them is my original work but they are based on examples developed by students in the lab.

If you want a reference paper, you could look at [Mellinger's 2011 ICRA](https://ieeexplore.ieee.org/document/5980409)

https://github.com/JacopoPan/gym-pybullet-drones/blob/c53b703a852209fc1015fc9cea49e7cc7a3cb469/assignments/aer1216_fall2020_hw1_ctrl.py#L69
https://github.com/JacopoPan/gym-pybullet-drones/blob/c53b703a852209fc1015fc9cea49e7cc7a3cb469/assignments/aer1216_fall2020_hw2_ctrl.py#L105
https://github.com/JacopoPan/gym-pybullet-drones/blob/c53b703a852209fc1015fc9cea49e7cc7a3cb469/gym_pybullet_drones/control/SimplePIDControl.py#L65
https://github.com/JacopoPan/gym-pybullet-drones/blob/c53b703a852209fc1015fc9cea49e7cc7a3cb469/gym_pybullet_drones/control/DSLPIDControl.py#L68
